application: errbot
version: 1
runtime: go
api_version: go1

handlers:
- url: /repos.json
  static_files: static/repos.json
  upload: static/repos.json
- url: /.well-known/acme-challenge/se7cy406RATKtEUcPihtPCOqrxOxbEwwEqGd8m1a6k8
  static_files: static/challenge
  upload: static/challenge

- url: /.*
  script: _go_app

